# Generated by Django 3.1.7 on 2021-02-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usertests', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionThemas',
            new_name='QuestionThemes',
        ),
    ]
