# Generated by Django 3.1.7 on 2021-02-20 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usertests', '0002_auto_20210220_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='questionauthor',
            options={'verbose_name': 'Автор вопроса', 'verbose_name_plural': 'Авторы вопросов'},
        ),
    ]
